### ISSUE TITLE
Python error: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by khoazero123** [strazzere/golang_loader_assist#14]
**Describe the bug**

I got this error with IDA Pro 7.6, Python 3.7.8, Python 3.8.10, Python 3.9.2, Python 3.11

```
golang_loader_assist.py: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "C:\Users\admin\Downloads\IDA Pro 7.6.210427 (x86,x64,ARM,ARM64,PPC,PPC64,MIPS)\x64_idapronw_hexarm64w_hexarmw_hexmipsw_hexppc64w_hexppcw_hexx64w_hexx86w_210427\python\3\ida_idaapi.py", line 616, in IDAPython_ExecScript
    exec(code, g)
  File "E:/www/golang_loader_assist.py", line 452, in <module>
    main()
  File "E:/www/golang_loader_assist.py", line 440, in main
    renamed = renamer_init()
  File "E:/www/golang_loader_assist.py", line 386, in renamer_init
    ida_bytes.create_strlit(func_name_addr, len(func_name), STRTYPE_C)
TypeError: object of type 'NoneType' has no len()
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - IDA version 7.6

**Binary or Golang code to reproduce against**
If you're able to write a snippet of golang code and/or provide an actual targeted binary, this would help immensely to reproduce the problems.

**Additional context**

**Comment by strazzere** [comment]
You'll either need to share the binary you're attempting to use this on or perform the debugging yourself. However the code is pretty simplistic;

```
            func_name_addr = idc.get_wide_dword(name_offset + start_ea + addr_size) + start_ea
            func_name = ida_bytes.get_strlit_contents(func_name_addr, -1, STRTYPE_C)
            ida_bytes.create_strlit(func_name_addr, len(func_name), STRTYPE_C)
```
The only way `func_name` is going to be a `NoneType` is if the `ida_bytes.get_strlit_contents` returns nothing. So either the line above it is deriving a `func_name_addr` which is bad, or the `get_strlit_contents` is returning `None` because the string is not there?
